### ISSUE TITLE
Error: Objects are not valid as a React child

### ISSUE THREAD

**Issue by Sandun-Isuru-Niraj** [fontlet/fontlet-explorer#91]
When I going to install a Font on the Windows. It throws this error. 

![image](https://user-images.githubusercontent.com/27560724/48599649-a5239300-e98e-11e8-9517-9e430e0485cc.png)

**Comment by gpetrioli** [comment]
This is two-fold. 

One is the reason React yells which is that it cannot render objects (*and when an error occurs it will be an object since they are created with `{message:'...', params: <actual_error>}`. This problem would occur in all platforms since it is React specific.

The solution would be in https://github.com/fontlet/fontlet-explorer/blob/4f5e4e95d67841e9e2d7c2baabd79d01d42bb82b/src/components/common/ErrorView.js#L15 to print `error.message` instead of `error`.

The other more important issue is why it actually fails to install the Font.

**Comment by thinkholic** [comment]
@gpetrioli thanks! for pointing out the issue with the `ErrorView` component. Anyway there is an another error which related to either `neDb` or installing fonts in Window. Probably a permission issue.

@Sandun-Isuru-Niraj ^

**Comment by gpetrioli** [comment]
Just a heads up: 

- On windows 10 pro i got the problem and it was related with `addInstalledFontToLocalCache` (*the font was installed though*)
- On windows 7 ultimate i get the opposite, it throws no error (*in fact it shows system notification that font was installed*) but font is actually not installed (*cannot see it in fonts folder, nor in apps i run later on*).

**Comment by thinkholic** [comment]
@gpetrioli 
Yes, Windows functionality is entire yet to finish. :). Haven't handle user rights or multi-font installing/uninstalling.

This is the solution we formulation as of now.  #47 
Love to hear if you got better suggestions.

**Comment by pathumego** [comment]
Thanks @gpetrioli Closing this now and will track the rest on #47
